// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBu02nMFfHdnInO-OVKd5Z09jL6Eermx_E',
    appId: '1:229107265725:web:f6daf70925801003bf87d4',
    messagingSenderId: '229107265725',
    projectId: 'hackathon-2022-7c673',
    authDomain: 'hackathon-2022-7c673.firebaseapp.com',
    databaseURL: 'https://hackathon-2022-7c673-default-rtdb.firebaseio.com',
    storageBucket: 'hackathon-2022-7c673.appspot.com',
    measurementId: 'G-DVM8EWLKHL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCUfd4so2YdaTCllgE2CKXgQsJY0NZJCtE',
    appId: '1:229107265725:android:443921d7e9e9fe6cbf87d4',
    messagingSenderId: '229107265725',
    projectId: 'hackathon-2022-7c673',
    databaseURL: 'https://hackathon-2022-7c673-default-rtdb.firebaseio.com',
    storageBucket: 'hackathon-2022-7c673.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDl3ngr6X4pTaC0PV6gqomHwMj7FWW9BQE',
    appId: '1:229107265725:ios:9050e36d905ac87ebf87d4',
    messagingSenderId: '229107265725',
    projectId: 'hackathon-2022-7c673',
    databaseURL: 'https://hackathon-2022-7c673-default-rtdb.firebaseio.com',
    storageBucket: 'hackathon-2022-7c673.appspot.com',
    iosClientId: '229107265725-v31j7l9rcpjtcub7b8fknh3l4ft5ksi1.apps.googleusercontent.com',
    iosBundleId: 'com.example.hackathon2022',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDl3ngr6X4pTaC0PV6gqomHwMj7FWW9BQE',
    appId: '1:229107265725:ios:9050e36d905ac87ebf87d4',
    messagingSenderId: '229107265725',
    projectId: 'hackathon-2022-7c673',
    databaseURL: 'https://hackathon-2022-7c673-default-rtdb.firebaseio.com',
    storageBucket: 'hackathon-2022-7c673.appspot.com',
    iosClientId: '229107265725-v31j7l9rcpjtcub7b8fknh3l4ft5ksi1.apps.googleusercontent.com',
    iosBundleId: 'com.example.hackathon2022',
  );
}
